name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: |
        npm install 
        npm run build
    - name: Deploy to tracking-system-admin.surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'tracking-system-admin.surge.sh'
        project: 'dist/'
        login: ${{ secrets.SURGE_LOGIN }}
        token: ${{ secrets.SURGE_TOKEN }}
